# Generated by Django 5.0.6 on 2026-07-17 15:44

import apps.core.ck_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('seo_title', models.CharField(blank=True, help_text='Page title for search engines. Max 70 characters.', max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Page description for search engines. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image shown when shared on social media. Recommended: 1200x630px.', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', apps.core.ck_field.CKEditor5Field(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('meeting', 'General Meeting'), ('workshop', 'Workshop / Training'), ('award', 'Award / Recognition'), ('protest', 'Press / Protest'), ('other', 'Other')], default='other', max_length=30, verbose_name='Event Type')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Location')),
                ('location_detail', models.TextField(blank=True, verbose_name='Location Details / Address')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Cover Image')),
                ('registration_link', models.URLField(blank=True, verbose_name='Registration / RSVP Link')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Role / Organization')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_speakers/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
