# Generated by Django 5.0.6 on 2026-07-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('role', models.CharField(max_length=200, verbose_name='Role / Designation')),
                ('category', models.CharField(choices=[('president', 'President'), ('working_president', 'Working President'), ('secretary_general', 'Secretary General'), ('treasurer', 'Treasurer'), ('vice_president', 'Vice President'), ('joint_secretary', 'Joint Secretary'), ('executive_member', 'Executive Member'), ('zonal_coordinator', 'Zonal Coordinator'), ('patron', 'Patron'), ('advisor', 'Advisor')], default='executive_member', max_length=50, verbose_name='Category')),
                ('state', models.CharField(blank=True, choices=[('AN', 'Andaman & Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu & Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2, verbose_name='State')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Zone')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bearers/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('show_contact', models.BooleanField(default=False, help_text='If checked, email/phone will be visible to public.', verbose_name='Show Contact Publicly')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='Term Start')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='Term End')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Office Bearer',
                'verbose_name_plural': 'Office Bearers',
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StateUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Unit Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('state', models.CharField(choices=[('AN', 'Andaman & Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu & Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2, unique=True, verbose_name='State / UT')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Established Year')),
                ('description', models.TextField(blank=True, verbose_name='About the Unit')),
                ('address', models.TextField(blank=True, verbose_name='Office Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='state_units/', verbose_name='Cover Image')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Member Count')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'State Unit',
                'verbose_name_plural': 'State Units',
                'ordering': ['order', 'state'],
            },
        ),
        migrations.CreateModel(
            name='StateUnitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('role', models.CharField(max_length=200, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='state_members/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('state_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.stateunit', verbose_name='State Unit')),
            ],
            options={
                'verbose_name': 'State Unit Member',
                'verbose_name_plural': 'State Unit Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
