# Generated by Django 5.0.6 on 2026-07-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateunit',
            options={'ordering': ['order', 'state'], 'verbose_name': 'City Unit', 'verbose_name_plural': 'City Units'},
        ),
        migrations.AlterModelOptions(
            name='stateunitmember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'City Unit Member', 'verbose_name_plural': 'City Unit Members'},
        ),
        migrations.AlterField(
            model_name='officebearer',
            name='state',
            field=models.CharField(blank=True, choices=[('LKO', 'Lucknow'), ('KNP', 'Kanpur'), ('VAR', 'Varanasi'), ('AGR', 'Agra'), ('PRY', 'Prayagraj'), ('MRT', 'Meerut'), ('GZB', 'Ghaziabad'), ('NOI', 'Noida / Greater Noida'), ('GKP', 'Gorakhpur'), ('BRL', 'Bareilly'), ('ALG', 'Aligarh'), ('MRD', 'Moradabad'), ('SHR', 'Saharanpur'), ('MTH', 'Mathura'), ('FBD', 'Faizabad / Ayodhya'), ('JHP', 'Jhansi'), ('RBR', 'Raebareli'), ('STG', 'Sultanpur'), ('AZG', 'Azamgarh'), ('MDR', 'Mirzapur'), ('BLI', 'Ballia'), ('DDB', 'Deoria'), ('BRN', 'Bulandshahr'), ('HAP', 'Hapur'), ('SHM', 'Shamli'), ('MZN', 'Muzaffarnagar'), ('BDN', 'Budaun'), ('ETW', 'Etawah'), ('AUR', 'Auraiya'), ('JPR', 'Jaunpur'), ('CND', 'Chandauli'), ('SNP', 'Sonbhadra'), ('PTN', 'Pratapgarh'), ('AMB', 'Ambedkar Nagar'), ('LKP', 'Lakhimpur Kheri'), ('HRD', 'Hardoi')], max_length=3, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='stateunit',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='city_units/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='stateunit',
            name='state',
            field=models.CharField(choices=[('LKO', 'Lucknow'), ('KNP', 'Kanpur'), ('VAR', 'Varanasi'), ('AGR', 'Agra'), ('PRY', 'Prayagraj'), ('MRT', 'Meerut'), ('GZB', 'Ghaziabad'), ('NOI', 'Noida / Greater Noida'), ('GKP', 'Gorakhpur'), ('BRL', 'Bareilly'), ('ALG', 'Aligarh'), ('MRD', 'Moradabad'), ('SHR', 'Saharanpur'), ('MTH', 'Mathura'), ('FBD', 'Faizabad / Ayodhya'), ('JHP', 'Jhansi'), ('RBR', 'Raebareli'), ('STG', 'Sultanpur'), ('AZG', 'Azamgarh'), ('MDR', 'Mirzapur'), ('BLI', 'Ballia'), ('DDB', 'Deoria'), ('BRN', 'Bulandshahr'), ('HAP', 'Hapur'), ('SHM', 'Shamli'), ('MZN', 'Muzaffarnagar'), ('BDN', 'Budaun'), ('ETW', 'Etawah'), ('AUR', 'Auraiya'), ('JPR', 'Jaunpur'), ('CND', 'Chandauli'), ('SNP', 'Sonbhadra'), ('PTN', 'Pratapgarh'), ('AMB', 'Ambedkar Nagar'), ('LKP', 'Lakhimpur Kheri'), ('HRD', 'Hardoi')], max_length=3, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='stateunitmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_members/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='stateunitmember',
            name='state_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.stateunit', verbose_name='City Unit'),
        ),
    ]
