# Generated by Django 5.0.6 on 2026-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_stateunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebearer',
            name='state',
            field=models.CharField(blank=True, choices=[('AGR', 'Agra'), ('ALG', 'Aligarh'), ('AMB', 'Ambedkar Nagar'), ('AMT', 'Amethi'), ('AMR', 'Amroha'), ('AYD', 'Ayodhya (Faizabad)'), ('AZG', 'Azamgarh'), ('BDN', 'Badaun'), ('BGP', 'Bagpat'), ('BAH', 'Bahraich'), ('BLI', 'Ballia'), ('BRM', 'Balrampur'), ('BND', 'Banda'), ('BAR', 'Barabanki'), ('BRL', 'Bareilly'), ('BST', 'Basti'), ('BIJ', 'Bijnor'), ('BRN', 'Bulandshahr'), ('CND', 'Chandauli'), ('CHT', 'Chitrakoot'), ('DDB', 'Deoria'), ('ETH', 'Etah'), ('ETW', 'Etawah'), ('FAR', 'Farrukhabad'), ('FTP', 'Fatehpur'), ('FZB', 'Firozabad'), ('GBN', 'Gautam Buddha Nagar (Noida)'), ('GZB', 'Ghaziabad'), ('GPR', 'Ghazipur'), ('GND', 'Gonda'), ('GKP', 'Gorakhpur'), ('HMR', 'Hamirpur'), ('HAP', 'Hapur'), ('HRD', 'Hardoi'), ('HTP', 'Hathras'), ('JAL', 'Jalaun'), ('JPR', 'Jaunpur'), ('JHS', 'Jhansi'), ('KNN', 'Kannauj'), ('KNP', 'Kanpur Nagar'), ('KDH', 'Kanpur Dehat'), ('KSG', 'Kasganj'), ('KSH', 'Kaushambi'), ('KHR', 'Kheri (Lakhimpur)'), ('KSN', 'Kushinagar'), ('LLT', 'Lalitpur'), ('LKO', 'Lucknow'), ('MHB', 'Maharajganj'), ('MHP', 'Mahoba'), ('MNP', 'Mainpuri'), ('MTH', 'Mathura'), ('MAU', 'Mau'), ('MRT', 'Meerut'), ('MDR', 'Mirzapur'), ('MRD', 'Moradabad'), ('MZN', 'Muzaffarnagar'), ('PBH', 'Pilibhit'), ('PTN', 'Pratapgarh'), ('PRY', 'Prayagraj (Allahabad)'), ('RBR', 'Raebareli'), ('RAM', 'Rampur'), ('SHJ', 'Saharanpur'), ('SMB', 'Sambhal'), ('SKN', 'Sant Kabir Nagar'), ('BHD', 'Sant Ravidas Nagar'), ('SHP', 'Shahjahanpur'), ('SHM', 'Shamli'), ('SRV', 'Shravasti'), ('SDH', 'Siddharthnagar'), ('STP', 'Sitapur'), ('SNB', 'Sonbhadra'), ('STG', 'Sultanpur'), ('UNO', 'Unnao'), ('VAR', 'Varanasi')], max_length=3, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='stateunit',
            name='state',
            field=models.CharField(choices=[('AGR', 'Agra'), ('ALG', 'Aligarh'), ('AMB', 'Ambedkar Nagar'), ('AMT', 'Amethi'), ('AMR', 'Amroha'), ('AYD', 'Ayodhya (Faizabad)'), ('AZG', 'Azamgarh'), ('BDN', 'Badaun'), ('BGP', 'Bagpat'), ('BAH', 'Bahraich'), ('BLI', 'Ballia'), ('BRM', 'Balrampur'), ('BND', 'Banda'), ('BAR', 'Barabanki'), ('BRL', 'Bareilly'), ('BST', 'Basti'), ('BIJ', 'Bijnor'), ('BRN', 'Bulandshahr'), ('CND', 'Chandauli'), ('CHT', 'Chitrakoot'), ('DDB', 'Deoria'), ('ETH', 'Etah'), ('ETW', 'Etawah'), ('FAR', 'Farrukhabad'), ('FTP', 'Fatehpur'), ('FZB', 'Firozabad'), ('GBN', 'Gautam Buddha Nagar (Noida)'), ('GZB', 'Ghaziabad'), ('GPR', 'Ghazipur'), ('GND', 'Gonda'), ('GKP', 'Gorakhpur'), ('HMR', 'Hamirpur'), ('HAP', 'Hapur'), ('HRD', 'Hardoi'), ('HTP', 'Hathras'), ('JAL', 'Jalaun'), ('JPR', 'Jaunpur'), ('JHS', 'Jhansi'), ('KNN', 'Kannauj'), ('KNP', 'Kanpur Nagar'), ('KDH', 'Kanpur Dehat'), ('KSG', 'Kasganj'), ('KSH', 'Kaushambi'), ('KHR', 'Kheri (Lakhimpur)'), ('KSN', 'Kushinagar'), ('LLT', 'Lalitpur'), ('LKO', 'Lucknow'), ('MHB', 'Maharajganj'), ('MHP', 'Mahoba'), ('MNP', 'Mainpuri'), ('MTH', 'Mathura'), ('MAU', 'Mau'), ('MRT', 'Meerut'), ('MDR', 'Mirzapur'), ('MRD', 'Moradabad'), ('MZN', 'Muzaffarnagar'), ('PBH', 'Pilibhit'), ('PTN', 'Pratapgarh'), ('PRY', 'Prayagraj (Allahabad)'), ('RBR', 'Raebareli'), ('RAM', 'Rampur'), ('SHJ', 'Saharanpur'), ('SMB', 'Sambhal'), ('SKN', 'Sant Kabir Nagar'), ('BHD', 'Sant Ravidas Nagar'), ('SHP', 'Shahjahanpur'), ('SHM', 'Shamli'), ('SRV', 'Shravasti'), ('SDH', 'Siddharthnagar'), ('STP', 'Sitapur'), ('SNB', 'Sonbhadra'), ('STG', 'Sultanpur'), ('UNO', 'Unnao'), ('VAR', 'Varanasi')], max_length=3, unique=True, verbose_name='City'),
        ),
    ]
