# Generated by Django 5.0.6 on 2026-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_officebearer_state_alter_stateunit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='officebearer',
            name='is_national',
            field=models.BooleanField(default=False, help_text='Mark this person as a national-level office bearer for homepage display.', verbose_name='National Office Bearer'),
        ),
    ]
