# Generated by Django 5.0.6 on 2026-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body / Details')),
                ('link', models.URLField(blank=True, help_text='Optional: link this announcement to a page or document.', verbose_name='Link URL')),
                ('link_label', models.CharField(blank=True, default='Read More', max_length=100, verbose_name='Link Label')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide after this date. Leave blank to never expire.', null=True, verbose_name='Expires At')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('site_name', models.CharField(default='National Union of Journalists (India)', max_length=200, verbose_name='Site Name')),
                ('site_short_name', models.CharField(default='NUJ India', max_length=50, verbose_name='Short Name')),
                ('tagline', models.CharField(blank=True, help_text='One-line mission/tagline shown in hero and metadata.', max_length=300, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('logo_dark', models.ImageField(blank=True, help_text='Alternate logo for dark backgrounds.', null=True, upload_to='site/', verbose_name='Logo (Dark Mode)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('office_address', models.TextField(blank=True, verbose_name='Office Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='General Email')),
                ('membership_email', models.EmailField(blank=True, max_length=254, verbose_name='Membership Email')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Number')),
                ('footer_about', models.TextField(blank=True, help_text='Short description shown in footer.', verbose_name='Footer About Text')),
                ('copyright_text', models.CharField(blank=True, max_length=300, verbose_name='Copyright Text')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Total Members')),
                ('state_units_count', models.PositiveIntegerField(default=36, verbose_name='State Units')),
                ('years_of_service', models.PositiveIntegerField(default=0, verbose_name='Years of Service')),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g., G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('google_search_console', models.TextField(blank=True, help_text='Paste the full meta tag here.', verbose_name='Google Search Console Verification')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
