# Generated by Django 5.0.6 on 2026-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='National Union of Journalists (Uttar Pradesh)', max_length=200, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_short_name',
            field=models.CharField(default='NUJ UP', max_length=50, verbose_name='Short Name'),
        ),
    ]
