# Generated by Django 5.0.6 on 2026-07-17 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class name.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(help_text='Accepted: PDF, DOC, DOCX', upload_to='documents/%Y/%m/', verbose_name='File (PDF/DOC)')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of the document for filtering purposes.', null=True, verbose_name='Year')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured (shown on homepage)')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Download Count')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-published_at'],
            },
        ),
    ]
