# Generated by Django 5.0.6 on 2026-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reference_number', models.CharField(blank=True, help_text='Auto-generated on submission.', max_length=20, unique=True, verbose_name='Reference Number')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('state', models.CharField(choices=[('AN', 'Andaman & Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CG', 'Chhattisgarh'), ('DN', 'Dadra & Nagar Haveli and Daman & Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu & Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='PIN Code')),
                ('designation', models.CharField(max_length=200, verbose_name='Current Designation')),
                ('organization', models.CharField(max_length=300, verbose_name='Current Organization / Publication')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Journalism Experience')),
                ('membership_type', models.CharField(choices=[('ordinary', 'Ordinary Member'), ('associate', 'Associate Member'), ('honorary', 'Honorary Member')], default='ordinary', max_length=20, verbose_name='Membership Type')),
                ('id_proof', models.FileField(blank=True, help_text='Upload Aadhaar, PAN, Passport, or Voter ID.', null=True, upload_to='membership/id_proofs/%Y/', verbose_name='Identity Proof (PDF/JPG)')),
                ('press_card', models.FileField(blank=True, null=True, upload_to='membership/press_cards/%Y/', verbose_name='Press Card / Accreditation (PDF/JPG)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membership/photos/%Y/', verbose_name='Passport-size Photo')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], default='draft', max_length=30, verbose_name='Application Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — not visible to applicant.', verbose_name='Admin Notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('honeypot', models.CharField(blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
