# Generated by Django 5.0.6 on 2026-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='state',
            field=models.CharField(choices=[('LKO', 'Lucknow'), ('KNP', 'Kanpur'), ('VAR', 'Varanasi'), ('AGR', 'Agra'), ('PRY', 'Prayagraj'), ('MRT', 'Meerut'), ('GZB', 'Ghaziabad'), ('NOI', 'Noida / Greater Noida'), ('GKP', 'Gorakhpur'), ('BRL', 'Bareilly'), ('ALG', 'Aligarh'), ('MRD', 'Moradabad'), ('SHR', 'Saharanpur'), ('MTH', 'Mathura'), ('FBD', 'Faizabad / Ayodhya'), ('JHP', 'Jhansi'), ('RBR', 'Raebareli'), ('STG', 'Sultanpur'), ('AZG', 'Azamgarh'), ('MDR', 'Mirzapur'), ('BLI', 'Ballia'), ('DDB', 'Deoria'), ('BRN', 'Bulandshahr'), ('HAP', 'Hapur'), ('SHM', 'Shamli'), ('MZN', 'Muzaffarnagar'), ('BDN', 'Budaun'), ('ETW', 'Etawah'), ('AUR', 'Auraiya'), ('JPR', 'Jaunpur'), ('CND', 'Chandauli'), ('SNP', 'Sonbhadra'), ('PTN', 'Pratapgarh'), ('AMB', 'Ambedkar Nagar'), ('LKP', 'Lakhimpur Kheri'), ('HRD', 'Hardoi')], max_length=3, verbose_name='City'),
        ),
    ]
