# Generated by Django 5.0.6 on 2026-07-20 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershipapplication_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='state',
            field=models.CharField(choices=[('AGR', 'Agra'), ('ALG', 'Aligarh'), ('AMB', 'Ambedkar Nagar'), ('AMT', 'Amethi'), ('AMR', 'Amroha'), ('AYD', 'Ayodhya (Faizabad)'), ('AZG', 'Azamgarh'), ('BDN', 'Badaun'), ('BGP', 'Bagpat'), ('BAH', 'Bahraich'), ('BLI', 'Ballia'), ('BRM', 'Balrampur'), ('BND', 'Banda'), ('BAR', 'Barabanki'), ('BRL', 'Bareilly'), ('BST', 'Basti'), ('BIJ', 'Bijnor'), ('BRN', 'Bulandshahr'), ('CND', 'Chandauli'), ('CHT', 'Chitrakoot'), ('DDB', 'Deoria'), ('ETH', 'Etah'), ('ETW', 'Etawah'), ('FAR', 'Farrukhabad'), ('FTP', 'Fatehpur'), ('FZB', 'Firozabad'), ('GBN', 'Gautam Buddha Nagar (Noida)'), ('GZB', 'Ghaziabad'), ('GPR', 'Ghazipur'), ('GND', 'Gonda'), ('GKP', 'Gorakhpur'), ('HMR', 'Hamirpur'), ('HAP', 'Hapur'), ('HRD', 'Hardoi'), ('HTP', 'Hathras'), ('JAL', 'Jalaun'), ('JPR', 'Jaunpur'), ('JHS', 'Jhansi'), ('KNN', 'Kannauj'), ('KNP', 'Kanpur Nagar'), ('KDH', 'Kanpur Dehat'), ('KSG', 'Kasganj'), ('KSH', 'Kaushambi'), ('KHR', 'Kheri (Lakhimpur)'), ('KSN', 'Kushinagar'), ('LLT', 'Lalitpur'), ('LKO', 'Lucknow'), ('MHB', 'Maharajganj'), ('MHP', 'Mahoba'), ('MNP', 'Mainpuri'), ('MTH', 'Mathura'), ('MAU', 'Mau'), ('MRT', 'Meerut'), ('MDR', 'Mirzapur'), ('MRD', 'Moradabad'), ('MZN', 'Muzaffarnagar'), ('PBH', 'Pilibhit'), ('PTN', 'Pratapgarh'), ('PRY', 'Prayagraj (Allahabad)'), ('RBR', 'Raebareli'), ('RAM', 'Rampur'), ('SHJ', 'Saharanpur'), ('SMB', 'Sambhal'), ('SKN', 'Sant Kabir Nagar'), ('BHD', 'Sant Ravidas Nagar'), ('SHP', 'Shahjahanpur'), ('SHM', 'Shamli'), ('SRV', 'Shravasti'), ('SDH', 'Siddharthnagar'), ('STP', 'Sitapur'), ('SNB', 'Sonbhadra'), ('STG', 'Sultanpur'), ('UNO', 'Unnao'), ('VAR', 'Varanasi')], max_length=3, verbose_name='City'),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('member_id', models.CharField(blank=True, help_text='Auto-generated unique member number.', max_length=20, unique=True, verbose_name='Member ID')),
                ('membership_type', models.CharField(choices=[('ordinary', 'Ordinary Member'), ('associate', 'Associate Member'), ('honorary', 'Honorary Member')], default='ordinary', max_length=20, verbose_name='Membership Type')),
                ('city', models.CharField(blank=True, choices=[('AGR', 'Agra'), ('ALG', 'Aligarh'), ('AMB', 'Ambedkar Nagar'), ('AMT', 'Amethi'), ('AMR', 'Amroha'), ('AYD', 'Ayodhya (Faizabad)'), ('AZG', 'Azamgarh'), ('BDN', 'Badaun'), ('BGP', 'Bagpat'), ('BAH', 'Bahraich'), ('BLI', 'Ballia'), ('BRM', 'Balrampur'), ('BND', 'Banda'), ('BAR', 'Barabanki'), ('BRL', 'Bareilly'), ('BST', 'Basti'), ('BIJ', 'Bijnor'), ('BRN', 'Bulandshahr'), ('CND', 'Chandauli'), ('CHT', 'Chitrakoot'), ('DDB', 'Deoria'), ('ETH', 'Etah'), ('ETW', 'Etawah'), ('FAR', 'Farrukhabad'), ('FTP', 'Fatehpur'), ('FZB', 'Firozabad'), ('GBN', 'Gautam Buddha Nagar (Noida)'), ('GZB', 'Ghaziabad'), ('GPR', 'Ghazipur'), ('GND', 'Gonda'), ('GKP', 'Gorakhpur'), ('HMR', 'Hamirpur'), ('HAP', 'Hapur'), ('HRD', 'Hardoi'), ('HTP', 'Hathras'), ('JAL', 'Jalaun'), ('JPR', 'Jaunpur'), ('JHS', 'Jhansi'), ('KNN', 'Kannauj'), ('KNP', 'Kanpur Nagar'), ('KDH', 'Kanpur Dehat'), ('KSG', 'Kasganj'), ('KSH', 'Kaushambi'), ('KHR', 'Kheri (Lakhimpur)'), ('KSN', 'Kushinagar'), ('LLT', 'Lalitpur'), ('LKO', 'Lucknow'), ('MHB', 'Maharajganj'), ('MHP', 'Mahoba'), ('MNP', 'Mainpuri'), ('MTH', 'Mathura'), ('MAU', 'Mau'), ('MRT', 'Meerut'), ('MDR', 'Mirzapur'), ('MRD', 'Moradabad'), ('MZN', 'Muzaffarnagar'), ('PBH', 'Pilibhit'), ('PTN', 'Pratapgarh'), ('PRY', 'Prayagraj (Allahabad)'), ('RBR', 'Raebareli'), ('RAM', 'Rampur'), ('SHJ', 'Saharanpur'), ('SMB', 'Sambhal'), ('SKN', 'Sant Kabir Nagar'), ('BHD', 'Sant Ravidas Nagar'), ('SHP', 'Shahjahanpur'), ('SHM', 'Shamli'), ('SRV', 'Shravasti'), ('SDH', 'Siddharthnagar'), ('STP', 'Sitapur'), ('SNB', 'Sonbhadra'), ('STG', 'Sultanpur'), ('UNO', 'Unnao'), ('VAR', 'Varanasi')], max_length=3, verbose_name='City')),
                ('designation', models.CharField(blank=True, max_length=200, verbose_name='Designation')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Organization')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('bio', models.TextField(blank=True, verbose_name='Short Bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/%Y/', verbose_name='Profile Photo')),
                ('press_card', models.FileField(blank=True, null=True, upload_to='members/press_cards/%Y/', verbose_name='Press Card')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Active Member')),
                ('membership_valid_until', models.DateField(blank=True, null=True, verbose_name='Membership Valid Until')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to='membership.membershipapplication', verbose_name='Membership Application')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'ordering': ['member_id'],
            },
        ),
    ]
