# Generated by Django 5.0.6 on 2026-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membershipapplication_state_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='managed_city',
            field=models.CharField(blank=True, choices=[('AGR', 'Agra'), ('ALG', 'Aligarh'), ('AMB', 'Ambedkar Nagar'), ('AMT', 'Amethi'), ('AMR', 'Amroha'), ('AYD', 'Ayodhya (Faizabad)'), ('AZG', 'Azamgarh'), ('BDN', 'Badaun'), ('BGP', 'Bagpat'), ('BAH', 'Bahraich'), ('BLI', 'Ballia'), ('BRM', 'Balrampur'), ('BND', 'Banda'), ('BAR', 'Barabanki'), ('BRL', 'Bareilly'), ('BST', 'Basti'), ('BIJ', 'Bijnor'), ('BRN', 'Bulandshahr'), ('CND', 'Chandauli'), ('CHT', 'Chitrakoot'), ('DDB', 'Deoria'), ('ETH', 'Etah'), ('ETW', 'Etawah'), ('FAR', 'Farrukhabad'), ('FTP', 'Fatehpur'), ('FZB', 'Firozabad'), ('GBN', 'Gautam Buddha Nagar (Noida)'), ('GZB', 'Ghaziabad'), ('GPR', 'Ghazipur'), ('GND', 'Gonda'), ('GKP', 'Gorakhpur'), ('HMR', 'Hamirpur'), ('HAP', 'Hapur'), ('HRD', 'Hardoi'), ('HTP', 'Hathras'), ('JAL', 'Jalaun'), ('JPR', 'Jaunpur'), ('JHS', 'Jhansi'), ('KNN', 'Kannauj'), ('KNP', 'Kanpur Nagar'), ('KDH', 'Kanpur Dehat'), ('KSG', 'Kasganj'), ('KSH', 'Kaushambi'), ('KHR', 'Kheri (Lakhimpur)'), ('KSN', 'Kushinagar'), ('LLT', 'Lalitpur'), ('LKO', 'Lucknow'), ('MHB', 'Maharajganj'), ('MHP', 'Mahoba'), ('MNP', 'Mainpuri'), ('MTH', 'Mathura'), ('MAU', 'Mau'), ('MRT', 'Meerut'), ('MDR', 'Mirzapur'), ('MRD', 'Moradabad'), ('MZN', 'Muzaffarnagar'), ('PBH', 'Pilibhit'), ('PTN', 'Pratapgarh'), ('PRY', 'Prayagraj (Allahabad)'), ('RBR', 'Raebareli'), ('RAM', 'Rampur'), ('SHJ', 'Saharanpur'), ('SMB', 'Sambhal'), ('SKN', 'Sant Kabir Nagar'), ('BHD', 'Sant Ravidas Nagar'), ('SHP', 'Shahjahanpur'), ('SHM', 'Shamli'), ('SRV', 'Shravasti'), ('SDH', 'Siddharthnagar'), ('STP', 'Sitapur'), ('SNB', 'Sonbhadra'), ('STG', 'Sultanpur'), ('UNO', 'Unnao'), ('VAR', 'Varanasi')], help_text='For city_admin role only — which city this person manages.', max_length=3, verbose_name='Managed City'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('city_admin', 'City Admin'), ('super_admin', 'Super Admin')], default='member', help_text='member = normal access; city_admin = manage one city; super_admin = manage everything', max_length=20, verbose_name='Portal Role'),
        ),
    ]
