# Generated by Django 5.0.6 on 2026-07-17 15:44

import apps.core.ck_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('announcement_ticker', 'Announcement Ticker'), ('stats', 'Stats Bar'), ('news_press', 'News & Press Releases'), ('leadership_message', 'Leadership Message'), ('quick_links', 'Quick Links'), ('events', 'Upcoming Events'), ('documents', 'Important Documents')], max_length=50, unique=True, verbose_name='Section Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('hero_title', models.CharField(blank=True, max_length=300, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Hero Subtitle / Mission Statement')),
                ('hero_cta_label', models.CharField(blank=True, default='Apply for Membership', max_length=100, verbose_name='Primary CTA Label')),
                ('hero_cta_url', models.CharField(blank=True, default='/membership/', max_length=200, verbose_name='Primary CTA URL')),
                ('hero_secondary_cta_label', models.CharField(blank=True, max_length=100, verbose_name='Secondary CTA Label')),
                ('hero_secondary_cta_url', models.CharField(blank=True, max_length=200, verbose_name='Secondary CTA URL')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/hero/', verbose_name='Hero Background Image')),
                ('message_author_name', models.CharField(blank=True, max_length=200, verbose_name='Message Author Name')),
                ('message_author_role', models.CharField(blank=True, max_length=200, verbose_name='Message Author Role')),
                ('message_author_photo', models.ImageField(blank=True, null=True, upload_to='home/messages/', verbose_name='Author Photo')),
                ('message_body', models.TextField(blank=True, verbose_name='Message Body (excerpt)')),
                ('message_link', models.CharField(blank=True, max_length=200, verbose_name='Read Full Message Link')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('seo_title', models.CharField(blank=True, help_text='Page title for search engines. Max 70 characters.', max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Page description for search engines. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image shown when shared on social media. Recommended: 1200x630px.', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('key', models.CharField(choices=[('about', 'About NUJ India'), ('history', 'History'), ('constitution', 'Constitution'), ('affiliations', 'Affiliations & Recognition'), ('vision_mission', 'Vision & Mission')], help_text='Unique identifier — links this record to a URL.', max_length=50, unique=True, verbose_name='Page Key')),
                ('title', models.CharField(max_length=300, verbose_name='Page Title')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtitle / Intro')),
                ('body', apps.core.ck_field.CKEditor5Field(verbose_name='Body Content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Cover Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author_name', models.CharField(max_length=200, verbose_name='Author Name')),
                ('author_role', models.CharField(blank=True, max_length=200, verbose_name='Role / Designation')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
