# Generated by Django 5.0.6 on 2026-07-17 15:44

import apps.core.ck_field
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('addressed_to', models.CharField(blank=True, max_length=300, verbose_name='Addressed To')),
                ('body', apps.core.ck_field.CKEditor5Field(verbose_name='Body / Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='newsroom/letters/', verbose_name='Attachment')),
                ('date_issued', models.DateField(verbose_name='Date Issued')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Letter / Statement',
                'verbose_name_plural': 'Letters & Statements',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='newsroom/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('category', models.CharField(choices=[('event', 'Event'), ('meeting', 'Meeting / Conference'), ('press', 'Press Activity'), ('award', 'Award / Recognition'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Upload Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Gallery',
                'ordering': ['-upload_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('color', models.CharField(blank=True, default='#1a2744', help_text='e.g. #c0392b — used as label color.', max_length=20, verbose_name='Color (hex)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('seo_title', models.CharField(blank=True, help_text='Page title for search engines. Max 70 characters.', max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Page description for search engines. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image shown when shared on social media. Recommended: 1200x630px.', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('summary', models.TextField(blank=True, max_length=400, verbose_name='Summary')),
                ('body', apps.core.ck_field.CKEditor5Field(verbose_name='Body')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='newsroom/press/', verbose_name='Cover Image')),
                ('attachment', models.FileField(blank=True, help_text='Upload a PDF version of the press release.', null=True, upload_to='newsroom/press/attachments/', verbose_name='Attachment (PDF)')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Press Release',
                'verbose_name_plural': 'Press Releases',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('seo_title', models.CharField(blank=True, help_text='Page title for search engines. Max 70 characters.', max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Page description for search engines. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image shown when shared on social media. Recommended: 1200x630px.', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, help_text='Short excerpt shown in list view. Max 400 characters.', max_length=400, verbose_name='Summary')),
                ('body', apps.core.ck_field.CKEditor5Field(verbose_name='Body')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='newsroom/news/', verbose_name='Cover Image')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author Name')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='newsroom.newscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
